struct PositionSearch {
    project_id                  int
    keyword                     string [optional]
}

struct UserPortfolio {
    projects                    []UserProject
}

struct Project {
    project_id                  int
    name                        string
}

struct UserProject extends Project {
    access_type                 AccessType
}

struct User {
    email                       string [optional]
    name                        string
    date_created                int
    user_id                     string
    default_language            Language [optional]
    default_gps_format          GPSFormat [optional]
    default_measurement_system  MeasurementSystem [optional]
    default_google_map_type     GoogleMapType [optional]
    needs_to_update_settings    bool [optional]
}

struct UserSettingsUpdate {
    user_id                     string
    default_language            Language
    default_gps_format          GPSFormat
    default_measurement_system  MeasurementSystem
    default_google_map_type     GoogleMapType
}

struct Position {
    position_id                 int
    project_id                  int
    position_properties         []PositionProperty
}

struct CreatePositionProperty {
    field_type                  FieldType
    name                        string
    value                       string
}

struct PositionProperty {
    field_type                  FieldType
    name                        string
    value                       string
    property_id                 int
    visible                     YesNo
}

enum YesNo {
    Y
    N
}

enum FieldType {
    NUMBER
    STRING
    IMAGE
    IMAGE_LIST
}

enum AccessType {
    OWNER
}

enum Language {
    EN_US
    ES_LA
    FR_FR
}

enum GPSFormat {
    DECIMAL
    DEGREE
    UTMWGS84
}

enum MeasurementSystem {
    METRIC
    IMPERIAL
}

enum GoogleMapType {
    ROADMAP
    SATELLITE
    HYBRID
    TERRAIN
}

interface SimpleMappingSystem {
    get_projects(userId string) UserPortfolio
    get_user_settings(userId string) User
    update_user_settings(update UserSettingsUpdate) bool
    add_project(projectName string, userId string) Project
    search_positions(search PositionSearch) []Position
    add_position(projectId int, properties []CreatePositionProperty, userId string) Position
//    get_position_fields()
//    add_position_field()
//    delete_position_field()
//    get_project_access()
//    delete_project_access()
//    add_project_access()
//    update_position()
//    delete_position()
//    update_position_fields()
//    add_positions()
}