struct Project {
    project_id                  int
    name                        string
}

struct UserProject extends Project {
    access_type                 AccessType
}

struct User {
    email                       string [optional]
    name                        string
    date_created                int
    user_id                     string
    default_language            Language [optional]
    default_gps_format          GPSFormat [optional]
    default_measurement_system  MeasurementSystem [optional]
    default_google_map_type     GoogleMapType [optional]
    needs_to_update_settings    bool [optional]
}

struct Position {
    position_id                 int
    project_id                  int
    position_properties         []PositionProperty
}

struct CreatePosition {
    position_properties         []CreatePositionProperty
}

struct CreatePositionProperty {
    name                        string
    value                       string
}

struct PositionProperty {
    property_id                 int
    field_type                  FieldType
    name                        string
    value                       string
    visible                     YesNo
}

struct PositionField {
    position_field_id           int
    field_type                  FieldType
    name                        string
    visible                     YesNo
}

struct ProjectAccess {
    project_access_id           int
    project_id                  int
    access_type                 AccessType
    user_id                     string [optional]
    email                       string [optional]
    link                        string [optional]
}

enum YesNo {
    Y
    N
}

enum FieldType {
    NUMBER
    STRING
    IMAGE
    IMAGE_LIST
}

enum AccessType {
    OWNER
    READONLY
    PUBLIC
}

enum Language {
    EN_US
    ES_LA
    FR_FR
}

enum GPSFormat {
    DECIMAL
    DEGREE
    UTMWGS84
}

enum MeasurementSystem {
    METRIC
    IMPERIAL
}

enum GoogleMapType {
    ROADMAP
    SATELLITE
    HYBRID
    TERRAIN
}

interface SimpleMappingSystem {
    add_position(userId string, projectId int, properties []CreatePositionProperty) Position

    add_position_field(userId string, projectId int, fieldType FieldType, name string) PositionField

    add_positions(userId string, projectId int, positions []CreatePosition) []Position

    add_project(userId string, projectName string) Project

    add_project_access(userId string, projectId int, accessType AccessType, language Language, measurementSys MeasurementSystem, gpsFormat GPSFormat, mapType GoogleMapType, message string, emails []string) []ProjectAccess

    delete_position(userId string, positionId int) bool

    delete_position_field(userId string, positionFieldId int) bool

    delete_project(userId string, projectId int) bool

    delete_project_access(userId string, projectAccessId int) bool

    get_position_fields(userId string, projectId int, suppressCoreFields bool, suppressFieldTypes []FieldType) []PositionField

    get_project_access(userId string, projectId int) []ProjectAccess

    get_projects(userId string) []UserProject

    get_user_settings(userId string) User

    search_positions(userId string, projectId int, keyword string) []Position

    update_position(userId string, positionId int, properties []CreatePositionProperty) Position

    update_position_fields(userId string, fields []PositionField) bool

    update_user_settings(userId string, defaultLanguage Language, defaultGpsFormat GPSFormat, defaultMeasurementSystem MeasurementSystem, defaultGoogleMapType GoogleMapType) bool
}